### ISSUE TITLE
数据库迁移文件不是最新的嘛

### ISSUE THREAD

**Issue by icwq** [gzydong/lumen-admin#1]
$menus = Permission::whereIn('type', [Permission::TYPE_DIR, Permission::TYPE_MENU])->orderBy('sort', 'asc')->get([
            'id', 'parent_id', 'type', 'title', 'path',
            'component', 'perms', 'icon', 'sort',
            'hidden',
            'is_frame as target'
        ])->toArray();

获取管理员授权的菜单中查询的字段在迁移文件中没有
Schema::create($permissionsTable, function (Blueprint $table) {
            $table->increments('id')->comment('权限ID');
            $table->unsignedInteger('parent_id')->default(0)->comment('父级权限ID');
            $table->tinyInteger('type')->default(0)->comment('权限类型[0:目录;1:菜单;2:权限;]');
            $table->string('route')->unique()->comment('权限路由');
            $table->string('display_name')->nullable()->comment('权限显示名称');
            $table->string('description')->nullable()->comment('权限描述');
            $table->dateTime('created_at')->comment('创建时间');
            $table->dateTime('updated_at')->comment('修改时间');

            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
            $table->engine = 'InnoDB';
        });

希望大佬可以给个回复谢谢

**Comment by gzydong** [comment]
迁移文件还没有做对应的修改

**Comment by icwq** [comment]
好的，第一次用lumen,刚部署在本地，登录和创建管理员等功能已经可以正常调用，就是rbac这里或许有修改，希望大佬早日更新，谢谢

**Comment by gzydong** [comment]
好的

**Comment by gzydong** [comment]
已更新
